name: 'Run rubocop with reviewdog'
description: '🐶 Run rubocop with reviewdog on pull requests to improve code review experience.'
author: 'mgrachev (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  rubocop_version:
    description: 'Rubocop version'
  rubocop_extensions:
    description: 'Rubocop extensions'
    default: 'rubocop-rails rubocop-performance rubocop-rspec rubocop-i18n rubocop-rake'
  rubocop_flags:
    description: 'Rubocop flags. (rubocop <rubocop_flags>)'
    default: ''
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'rubocop'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  workdir:
    description: "The directory from which to look for and run Rubocop. Default '.'"
    default: '.'
  bundled_rubocop:
    description: 'Enable if rubocop is bundled within another gem'
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.rubocop_version }}
    - ${{ inputs.rubocop_extensions }}
    - ${{ inputs.rubocop_flags }}
    - ${{ inputs.tool_name }}
    - ${{ inputs.level }}
    - ${{ inputs.reporter }}
    - ${{ inputs.filter_mode }}
    - ${{ inputs.fail_on_error }}
    - ${{ inputs.reviewdog_flags }}
    - ${{ inputs.workdir }}
    - ${{ inputs.bundled_rubocop }}
branding:
  icon: 'check-circle'
  color: 'red'
